services:
  bankiru.seo.request_listener:
    class: Bankiru\Seo\Listener\SeoRequestListener
    arguments:
    - "@bankiru.seo.master_seo_request"
    tags:
    - { name: kernel.event_listener, event: kernel.controller, method: onMasterRequest, priority: -256 }
