services:
  bankiru.seo.request_listener:
    class: Bankiru\Seo\Listener\SeoRequestListener
    arguments:
    - "@router"
    - "@bankiru.seo.master_seo_request"
    tags:
    - { name: kernel.event_listener, event: kernel.request, method: onMasterRequest, priority: 1000 }
