services:
  bankiru.seo.source_registry:
    class: Bankiru\Seo\Resolver\SourceRegistry

  bankiru.seo.destination_compiler:
    alias: bankiru.seo.destination_compiler.symfony_routing

  bankiru.seo.destination_compiler.symfony_routing:
    class: Bankiru\Seo\Destination\Compiler\SymfonyRouterCompiler
    arguments:
    - "@bankiru.seo.slug.delegated_normalizer"
    - "@?twig"
    - "@router"

  bankiru.seo.target_sorter:
    alias: bankiru.seo.matching_score_target_sorter

  bankiru.seo.static_page_repository:
    class: Bankiru\Seo\Integration\Local\StaticPageRepository

  bankiru.seo.static_target_repository:
    class: Bankiru\Seo\Integration\Local\StaticTargetRepository

  bankiru.seo.target_repository:
    alias: bankiru.seo.static_target_repository

  bankiru.seo.page_repository:
    alias: bankiru.seo.static_page_repository

  bankiru.seo.matching_score_target_sorter:
    class: Bankiru\Seo\Target\MatchScoreTargetSorter
    arguments:
    - "@bankiru.seo.target_repository"

  bankiru.seo.matcher:
    class: Bankiru\Seo\DestinationMatcher
    arguments:
    - "@bankiru.seo.target_sorter"
    - "@bankiru.seo.page_repository"

  bankiru.seo.link_generator:
    class: Bankiru\Seo\Resolver\ContainerLinkResolver

  bankiru.seo.slug.sluggable_normalizer:
    class: Bankiru\Seo\Destination\Normalizer\SluggableNormalizer
    tags:
    - { name: seo_slug_normalizer }

  bankiru.seo.slug.stringify_normalizer:
    class: Bankiru\Seo\Destination\Normalizer\StringifyNormalizer
    tags:
    - { name: seo_slug_normalizer, priority: 255 }

  bankiru.seo.slug.scalar_normalizer:
    class: Bankiru\Seo\Destination\Normalizer\ScalarNormalizer
    tags:
    - { name: seo_slug_normalizer, priority: -255 }

  bankiru.seo.slug.delegated_normalizer:
    class: Bankiru\Seo\Destination\Normalizer\DelegatingNormalizer
    arguments:
    - []

  bankiru.seo.static_link_resolver:
    class: Bankiru\Seo\Resolver\StaticLinkResolver
    tags:
    - name: seo_link_resolver

  bankiru.seo.target_link_resolver:
    class: Bankiru\Seo\Resolver\TargetLinkResolver
    arguments:
    - "@bankiru.seo.source_registry"
    - "@bankiru.seo.destination_compiler"
    tags:
    - name: seo_link_resolver

  bankiru.seo.master_seo_request:
    class: Bankiru\Seo\Listener\MasterSeoRequest
    arguments:
    - "@bankiru.seo.matcher"

